#!/usr/bin/env python3
"""
Validate Office event fixtures with LLMAspect.

This script loads the JSON fixtures generated by `generate_office_event_tests.py`,
injects each event's context state into a minimal LLMAspect setup (semantic_context
→ LLM → semantic_prediction), and records the natural language description returned
by the LLM client. It also computes a simple keyword coverage score against the
expected semantics (keywords field) so we can quantify whether the description
matches the scenario outline.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import torch

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from aonn.aspects.llm_aspect import LLMAspect
from aonn.aspects.mock_llm_client import MockLLMClient

try:
    from aonn.aspects.ollama_llm_client import OllamaLLMClient
except Exception:
    OllamaLLMClient = None  # type: ignore

from aonn.core.object import ObjectNode

try:
    from sentence_transformers import SentenceTransformer
    HAS_SENTENCE_TRANSFORMERS = True
except ImportError:
    HAS_SENTENCE_TRANSFORMERS = False
    SentenceTransformer = None  # type: ignore


def load_fixtures(path: Path) -> Dict[str, Dict]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        # If user provided a list instead of dict, convert
        tmp = {}
        for entry in data:
            tmp[entry["event_name"]] = entry
        return tmp
    return data


def build_llm_client(use_ollama: bool, sem_dim: int, args) -> object:
    if use_ollama:
        if OllamaLLMClient is None:
            raise RuntimeError("OllamaLLMClient unavailable; install requirements or disable --use-ollama.")
        return OllamaLLMClient(
            input_dim=sem_dim,
            output_dim=sem_dim,
            base_url=args.ollama_base_url,
            model=args.ollama_model,
            embedding_model=args.ollama_embedding_model or args.ollama_model,
            summary_size=args.summary_size,
            max_tokens=args.max_tokens,
            temperature=args.temperature,
            timeout=args.ollama_timeout,
            device=torch.device(args.device),
            verbose=args.verbose,
        )
    # fallback mock client (deterministic)
    return MockLLMClient(input_dim=sem_dim, output_dim=sem_dim, hidden_dims=[256, 512, 256], device=torch.device(args.device))


def keyword_score(
    text: str,
    keywords: List[str],
    description: str = "",
    expectations: List[str] = None,
    use_semantic: bool = True,
    similarity_threshold: float = 0.3,
) -> Tuple[float, List[str], List[str], Dict[str, float]]:
    """
    Compute keyword coverage using semantic similarity instead of exact string matching.
    
    Args:
        text: LLM generated text
        keywords: List of expected keywords
        description: Event description (for context)
        expectations: List of expectations (for context)
        use_semantic: Whether to use semantic similarity (requires sentence-transformers)
        similarity_threshold: Minimum cosine similarity to consider a match (default 0.3)
    
    Returns:
        (coverage_ratio, matched_keywords, missing_keywords, keyword_similarities)
    """
    if not keywords:
        return 0.0, [], [], {}
    
    expectations = expectations or []
    keyword_similarities = {}
    
    if use_semantic and HAS_SENTENCE_TRANSFORMERS:
        try:
            # Use a lightweight model for fast similarity computation
            model = SentenceTransformer('all-MiniLM-L6-v2')
            
            # Embed the LLM text
            text_embedding = model.encode(text, convert_to_tensor=True)
            
            # Embed each keyword
            matched = []
            missing = []
            
            for kw in keywords:
                # Embed the keyword
                kw_embedding = model.encode(kw, convert_to_tensor=True)
                
                # Compute cosine similarity
                from torch.nn.functional import cosine_similarity
                similarity = cosine_similarity(text_embedding.unsqueeze(0), kw_embedding.unsqueeze(0)).item()
                keyword_similarities[kw] = similarity
                
                # Also check if keyword appears in description/expectations for context
                context_text = f"{description} {' '.join(expectations)}"
                if context_text:
                    context_embedding = model.encode(context_text, convert_to_tensor=True)
                    context_sim = cosine_similarity(text_embedding.unsqueeze(0), context_embedding.unsqueeze(0)).item()
                    # Boost similarity if keyword is semantically related to context
                    if context_sim > 0.4:
                        similarity = max(similarity, context_sim * 0.7)
                
                if similarity >= similarity_threshold:
                    matched.append(kw)
                else:
                    missing.append(kw)
            
            coverage = len(matched) / len(keywords) if keywords else 0.0
            return coverage, matched, missing, keyword_similarities
            
        except Exception as e:
            import warnings
            warnings.warn(f"Semantic similarity computation failed: {e}, falling back to exact match")
            use_semantic = False
    
    # Fallback to exact string matching
    tlower = text.lower()
    matched = []
    missing = []
    for kw in keywords:
        if kw.lower() in tlower:
            matched.append(kw)
            keyword_similarities[kw] = 1.0
        else:
            missing.append(kw)
            keyword_similarities[kw] = 0.0
    coverage = len(matched) / len(keywords) if keywords else 0.0
    return coverage, matched, missing, keyword_similarities


def validate_event(
    event_name: str,
    payload: Dict,
    llm_aspect: LLMAspect,
    device: torch.device,
) -> Dict:
    sem_dim = llm_aspect.llm_client.input_dim if hasattr(llm_aspect.llm_client, "input_dim") else len(payload["state_vectors"]["context"])
    context_vec = torch.tensor(payload["state_vectors"]["context"], dtype=torch.float32, device=device)
    if context_vec.numel() < sem_dim:
        pad = torch.zeros(sem_dim - context_vec.numel(), device=device)
        context_vec = torch.cat([context_vec, pad])
    elif context_vec.numel() > sem_dim:
        context_vec = context_vec[:sem_dim]

    context_obj = ObjectNode("semantic_context", sem_dim, device=device)
    pred_obj = ObjectNode("semantic_prediction", sem_dim, device=device)
    context_obj.set_state(context_vec)
    pred_obj.set_state(torch.zeros(sem_dim, device=device))
    metadata = payload.get("context_metadata") or {
        "text": payload.get("description", ""),
        "keywords": payload.get("keywords", []),
        "expectations": payload.get("expectations", []),
    }
    context_obj.set_metadata(metadata)
    objects = {"semantic_context": context_obj, "semantic_prediction": pred_obj}

    llm_aspect.set_iteration_info(iteration_idx=0, is_last_iter=True, step_counter=0)
    with torch.no_grad():
        _ = llm_aspect.forward(objects, iteration_idx=0, is_last_iter=True)
    generated_text = getattr(llm_aspect.llm_client, "_last_generated_text", "")

    # 在系统外部进行语义匹配（不破坏马尔可夫毯原则）
    # 期望关键词来自外部测试数据，不是系统内部状态
    expected_keywords = payload.get("keywords", [])
    context_description = payload.get("description", "")
    expectations = payload.get("expectations", [])
    
    # 使用 LLMAspect 的语义相似度计算方法（作为外部评估工具）
    coverage, matched, missing, keyword_similarities = llm_aspect.compute_semantic_similarity(
        llm_text=generated_text,
        expected_keywords=expected_keywords,
        context_description=context_description,
        expectations=expectations,
    )
    
    # 将结果存储到 LLMAspect（仅用于外部查询，不影响系统内部）
    match_result = {
        "coverage": coverage,
        "matched_keywords": matched,
        "missing_keywords": missing,
        "keyword_similarities": keyword_similarities,
        "llm_text": generated_text,
    }
    llm_aspect.set_semantic_match_result(match_result)

    return {
        "event": event_name,
        "description": payload.get("description", ""),
        "expectations": payload.get("expectations", []),
        "keywords": payload.get("keywords", []),
        "llm_text": generated_text,
        "keyword_coverage": coverage,
        "keywords_matched": matched,
        "keywords_missing": missing,
        "keyword_similarities": keyword_similarities,  # 添加相似度详情
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate Office event fixtures via LLMAspect")
    parser.add_argument("--input", type=Path, default=Path("data/office_event_tests/office_event_fixtures.json"))
    parser.add_argument("--output", type=Path, default=Path("data/office_event_tests/llm_validation_report.json"))
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--use-ollama", action="store_true", help="Use OllamaLLMClient instead of Mock client")
    parser.add_argument("--ollama-base-url", type=str, default="http://localhost:11434")
    parser.add_argument("--ollama-model", type=str, default="cogito:32b")
    parser.add_argument("--ollama-embedding-model", type=str, default=None)
    parser.add_argument("--ollama-timeout", type=float, default=120.0)
    parser.add_argument("--summary-size", type=int, default=8)
    parser.add_argument("--max-tokens", type=int, default=120)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--sem-dim", type=int, default=128)
    parser.add_argument("--max-events", type=int, default=None, help="Optional limit on number of events to evaluate")
    parser.add_argument("--similarity-threshold", type=float, default=0.3, help="Semantic similarity threshold for keyword matching")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    fixtures = load_fixtures(args.input)
    event_items = list(fixtures.items())
    if args.max_events is not None:
        event_items = event_items[: args.max_events]

    llm_client = build_llm_client(args.use_ollama, args.sem_dim, args)
    llm_aspect = LLMAspect(
        name="llm_aspect_validation",
        src_names=("semantic_context",),
        dst_names=("semantic_prediction",),
        llm_client=llm_client,
        llm_config={"summary_size": args.summary_size},
        call_frequency="every_iter",
        enable_semantic_matching=True,  # 启用内置语义匹配
        similarity_threshold=args.similarity_threshold if hasattr(args, 'similarity_threshold') else 0.3,
    )
    llm_aspect.llm_client = llm_client

    device = torch.device(args.device)
    report = []
    for name, payload in event_items:
        result = validate_event(name, payload, llm_aspect, device)
        report.append(result)
        print("=" * 80)
        print(f"Event: {name}")
        print(f"Description: {result['description']}")
        print(f"LLM: {result['llm_text']}")
        print(f"Keyword coverage: {result['keyword_coverage'] * 100:.1f}% (matched: {', '.join(result['keywords_matched']) or 'none'})")
        if result["keywords_missing"]:
            print(f"Missing keywords: {', '.join(result['keywords_missing'])}")
        if result.get("keyword_similarities"):
            print("Keyword similarities:")
            for kw, sim in result["keyword_similarities"].items():
                status = "✓" if kw in result["keywords_matched"] else "✗"
                print(f"  {status} {kw}: {sim:.3f}")
        print("Expectations:")
        for exp in result["expectations"]:
            print(f"  - {exp}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    print("=" * 80)
    print(f"Report saved to {args.output}")


if __name__ == "__main__":
    os.environ.setdefault("MPLCONFIGDIR", str(Path(".cache/matplotlib").resolve()))
    main()
